//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensOutfit
    {
        public int MensOutfitsID { get; set; }
        public int MensAccessoriesID { get; set; }
        public int MensBottomsID { get; set; }
        public int MensShoesID { get; set; }
        public int MensTopsID { get; set; }
    
        public virtual MensAccessory MensAccessory { get; set; }
        public virtual MensBottom MensBottom { get; set; }
        public virtual MensSho MensSho { get; set; }
        public virtual MensTop MensTop { get; set; }
    }
}
