//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardobeProjectEntities : DbContext
    {
        public WardobeProjectEntities()
            : base("name=WardobeProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MensAccessory> MensAccessories { get; set; }
        public virtual DbSet<MensBottom> MensBottoms { get; set; }
        public virtual DbSet<MensOutfit> MensOutfits { get; set; }
        public virtual DbSet<MensSho> MensShoes { get; set; }
        public virtual DbSet<MensTop> MensTops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WomensAccessory> WomensAccessories { get; set; }
        public virtual DbSet<WomensBottom> WomensBottoms { get; set; }
        public virtual DbSet<WomensOutfit> WomensOutfits { get; set; }
        public virtual DbSet<WomensSho> WomensShoes { get; set; }
        public virtual DbSet<WomensTop> WomensTops { get; set; }
    }
}
