//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WomensOutfit
    {
        public int WomensOutfitID { get; set; }
        public int WomensBottomsID { get; set; }
        public int WomensAccessoriesID { get; set; }
        public int WomensShoesID { get; set; }
        public int WomensTopsID { get; set; }
    
        public virtual WomensAccessory WomensAccessory { get; set; }
        public virtual WomensBottom WomensBottom { get; set; }
        public virtual WomensSho WomensSho { get; set; }
        public virtual WomensTop WomensTop { get; set; }
    }
}
